spring:
  redis:
    host: 172.17.6.117
  datasource:
    druid:
      learning:
        url: jdbc:mysql://172.17.6.117:3306/test?serverTimezone=UTC

rocketmq:
  name-server: 172.17.6.117:9876
  producer:
    group: group2