server:
  port: 8081

spring:
  application:
    name: spring-learning
  profiles:
    active: company
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      learning:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: root
        password: cafebabe
  redis:
    host: 172.17.6.117
    port: 6379
    database: 0
    password: cafebabe
    connect-timeout: 1000ms
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  sql:
    # 初始化配置
    init:
      # 始终初始化数据源
      mode: always
      # 脚本位置
      schema-locations: classpath:sql/init.sql
  main:
    allow-circular-references: true

learning:
  val:
    intVal: 12
    strVal: 'hello'
    boolVal: true
    decimalVal: 5.4
  complex:
    intArray:
      - 1
      - 2
      - 3
    strArray:
      - 'hi'
      - 'hello'
    integers: 4, 5, 6
    int2str:
      1: ljh
      2: lwk
    int-arr: 7, 8, 9

zuul:
  routes:
    cas-auth:
      path: /cas/auth
      url: https://ids.hit.edu.cn/authserver/login
    cas-check-ticket:
      path: /cas/check-ticket
      url: https://ids.hit.edu.cn/authserver/serviceValidate