spring:
  redis:
    host: my.vm
  datasource:
    druid:
      learning:
        url: jdbc:mysql://my.vm:3306/test?serverTimezone=UTC

rocketmq:
  name-server: my.vm:9876
  producer:
    group: group2