server:
  port: 8081

spring:
  application:
    name: spring-learning
  profiles:
    active: home
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      learning:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: root
        password: cafebabe
  redis:
    host: localhost
    port: 6379
    database: 0
    password: cafebabe
    connect-timeout: 1000ms
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  sql:
    # 初始化配置
    init:
      # 始终初始化数据源
      mode: never
      # 脚本位置
      schema-locations: classpath:sql/init_mysql.sql
  main:
    allow-circular-references: true
  messages:
    # 格式可以为以下两种：
    # - 目录/资源名
    # - 目录.资源名
    basename: i18n.message

mybatis-plus:
  type-aliases-package: cn.spring.learning.tx.mapper
  mapper-locations: classpath*:mybatis/mapper/*.xml

# 自定义配置
learning:
  val:
    intVal: 12
    strVal: 'hello'
    boolVal: true
    decimalVal: 5.4
  complex:
    int-array-yml:
      - 1
      - 2
    int-array-props[0]: 3
    int-array-props[1]: 4
    integer-list-csv: 5, 6
    int-arr-by-value: 7, 8
    str-array-yml:
      - 'hi'
      - 'hello'
    int-2-str-yml:
      1: ljh
      2: lwk

zuul:
  routes:
    cas-auth:
      path: /cas/auth
      url: https://ids.hit.edu.cn/authserver/login
    cas-check-ticket:
      path: /cas/check-ticket
      url: https://ids.hit.edu.cn/authserver/serviceValidate