server:
  port: 8081

spring:
  application:
    name: spring-learning
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      learning:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://my.vm:3306/test?serverTimezone=UTC
        username: root
        password: cafebabe
  rabbitmq:
    host: my.vm
    port: 5672
    username: user
    password: password
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
    virtual-host: '/'
#  mvc:
    # 静态资源路径，暂未调试成功，先不用该配置项吧
#    static-path-pattern: classpath:/static/
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  redis:
    host: my.vm
    port: 6379
    database: 0
    password: cafebabe
    connect-timeout: 1000ms
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  sql:
    # 初始化配置
    init:
      # 始终初始化数据源
      mode: never
      # 脚本位置
      schema-locations: classpath:sql/init_mysql.sql
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  messages:
    # 格式可以为以下两种：
    # - 目录/资源名
    # - 目录.资源名
    basename: i18n.message

mybatis-plus:
  type-aliases-package: cn.spring.learning.tx.mapper
  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  #  级别依次为【从高到低】：FATAL > ERROR > WARN > INFO > DEBUG > TRACE
  level:
    root: info
    cn.spring.learning.tx.**: debug
  file:
    path: 'log'
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %yellow(-%5p) - %blue(${PID}) --- traceId:[%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId}] %yellow([%t]) %green(%-40.40logger{39}) - [%file:%line] : %m%n '
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %yellow(-%5p) - %blue(${PID}) --- traceId:[%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId}] %yellow([%t]) %green(%-40.40logger{39}) - [%file:%line] : %m%n '

# 自定义配置
learning:
  val:
    intVal: 12
    strVal: 'hello'
    boolVal: true
    decimalVal: 5.4
  complex:
    int-array-yml:
      - 1
      - 2
    int-array-props[0]: 3
    int-array-props[1]: 4
    integer-list-csv: 5, 6
    int-arr-by-value: 7, 8
    str-array-yml:
      - 'hi'
      - 'hello'
    int-2-str-yml:
      1: ljh
      2: lwk

management:
  endpoints:
    web:
      exposure:
        include: restart

zuul:
  routes:
    cas-auth:
      path: /cas/auth
      url: https://ids.hit.edu.cn/authserver/login
    cas-check-ticket:
      path: /cas/check-ticket
      url: https://ids.hit.edu.cn/authserver/serviceValidate

rocketmq:
  name-server: my.vm:9876;my.vm:10876
  producer:
    group: group2